# Handlers for 000_server
# 
- name: Ensure that dagster-daemon service is restarted
  ansible.builtin.systemd_service:
    name: dagster-daemon.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: yes

- name: Ensure that dagster-webserver service is restarted
  ansible.builtin.systemd_service:
    name: dagster-webserver.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: yes

